/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_BD;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author jo199
 */
public class asignacionVehiculos extends javax.swing.JFrame {

    
    public asignacionVehiculos() {
        initComponents();
        cargarEmpleados();
        cargarDatos();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoa.png")).getImage());
        //cerrar();
        
    }
    public static String id_vehiculo="";
    public void cargarDatos(){
        asignacionVehiculosTabla rmvt = new asignacionVehiculosTabla();
        id_vehiculo = rmvt.id_vehiculo;
        System.out.println(id_vehiculo);
        try {
            
            Connection cn1 = Conection_BD.conexion_bd();
            PreparedStatement pst = cn1.prepareStatement("select "
                    + "b.no_inventario, "
                    + "b.marca, "
                    + "b.modelo, "
                    + "b.kilometraje, "
                    + "b.no_motor, "
                    + "b.no_placa, "
                    + "b.cilindraje, "
                    + "b.tarjeta, "
                    + "e.nombre_empleado "
                    + "from vehiculos b JOIN empleados e "
                    + "ON (b.id_empleado = e.id_empleado) "
                    + "WHERE b.id_vehiculo = "+id_vehiculo);
            ResultSet rs = pst.executeQuery();

            //modelo_tabla.
            while (rs.next()) {
                etq_noInventario.setText(rs.getObject(1).toString());
                etq_marca.setText(rs.getObject(2).toString());
                etq_modelo.setText(rs.getObject(3).toString());
                etq_kilometraje.setText(rs.getObject(4).toString());
                etq_motor.setText(rs.getObject(5).toString());
                etq_placa.setText(rs.getObject(6).toString());
                etq_cilindraje.setText(rs.getObject(7).toString());
                etq_tarjeta.setText(rs.getObject(8).toString());
                etq_encargado.setText(rs.getObject(9).toString());

            }

            cn1.close();
        } catch (Exception e) {
            System.out.println("Error al llenar tabla de equipos: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al mostrar informacion de productos", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    public void cargarEmpleados(){
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("SELECT nombre_empleado, clave_servidor_publico FROM empleados WHERE nombre_empleado not in ('almacen','transferencia')");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                barra_destino.addItem(rs.getObject(1).toString()+": "+rs.getObject(2).toString());
            }
            cn.close();
            
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra_destino = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        boton_asignar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNoInventario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbNoInventario1 = new javax.swing.JLabel();
        lbNoInventario2 = new javax.swing.JLabel();
        lbNoInventario3 = new javax.swing.JLabel();
        lbNoInventario4 = new javax.swing.JLabel();
        lbNoInventario6 = new javax.swing.JLabel();
        lbNoInventario5 = new javax.swing.JLabel();
        etq_kilometraje = new javax.swing.JLabel();
        etq_noInventario = new javax.swing.JLabel();
        etq_placa = new javax.swing.JLabel();
        etq_tarjeta = new javax.swing.JLabel();
        etq_marca = new javax.swing.JLabel();
        etq_motor = new javax.swing.JLabel();
        etq_modelo = new javax.swing.JLabel();
        etq_cilindraje = new javax.swing.JLabel();
        etq_encargado = new javax.swing.JLabel();
        boton_buscar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignacion de Vehiculos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        barra_destino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Destino");

        boton_asignar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_asignar.setText("Aceptar");
        boton_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_asignarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detalles del vehiculo");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Marca:");

        lbNoInventario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario.setText("No. Inventario:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        lbNoInventario1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario1.setText("No. Motor:");

        lbNoInventario2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario2.setText("Placa:");

        lbNoInventario3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario3.setText("Cilindraje:");

        lbNoInventario4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario4.setText("Tarjeta:");

        lbNoInventario6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario6.setText("Kilometraje");

        lbNoInventario5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbNoInventario5.setText("Encargado:");

        etq_kilometraje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_kilometraje.setText("jLabel4");

        etq_noInventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_noInventario.setText("jLabel4");

        etq_placa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_placa.setText("jLabel4");

        etq_tarjeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_tarjeta.setText("jLabel4");

        etq_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_marca.setText("jLabel4");

        etq_motor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_motor.setText("jLabel4");

        etq_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_modelo.setText("jLabel4");

        etq_cilindraje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_cilindraje.setText("jLabel4");

        etq_encargado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etq_encargado.setText("jLabel4");

        boton_buscar3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar3.setText("Regresar");
        boton_buscar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNoInventario4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNoInventario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNoInventario2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etq_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etq_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(etq_noInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNoInventario1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbNoInventario6, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(etq_marca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etq_motor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(etq_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNoInventario3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNoInventario5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etq_cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etq_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etq_encargado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(barra_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(boton_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(etq_marca))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNoInventario1)
                                .addComponent(etq_motor))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNoInventario6)
                                .addComponent(etq_kilometraje)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNoInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(etq_noInventario))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNoInventario2)
                                .addComponent(etq_placa))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNoInventario4)
                                .addComponent(etq_tarjeta))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etq_modelo)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNoInventario3)
                            .addComponent(etq_cilindraje))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNoInventario5)
                            .addComponent(etq_encargado))))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barra_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(boton_asignar)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_asignarActionPerformed
        //Se realiza la asignacion de bienes
        
//        System.out.println("Vehiculo "+id_vehiculo);
        asignacionVehiculosTabla abmt =  new asignacionVehiculosTabla();
        String empleado = barra_destino.getSelectedItem().toString();
        String datos_empleado[]=new String[2];
        StringTokenizer token = new StringTokenizer(empleado,":");
        while (token.hasMoreTokens()){
            datos_empleado[0] = token.nextToken();
        }                                                                                        
        System.out.println("Clave: "+datos_empleado[0]);
        System.out.println("Id del bien "+abmt.id_vehiculo);
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("SELECT id_empleado FROM empleados WHERE clave_servidor_publico like '%"+datos_empleado[0].trim()+"%'");
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String id_empleado=rs.getObject(1).toString();
                pst = cn.prepareStatement("UPDATE vehiculos SET id_empleado = ? WHERE id_vehiculo = "+abmt.id_vehiculo);
                pst.setString(1, id_empleado);
                pst.executeUpdate();
                System.out.println("Actualizacion exitosa!");
                
            }
            
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String fecha = dtf.format(LocalDateTime.now());
            pst = cn.prepareStatement("insert into movimientos (`tipo_movimiento`, `fecha`, `accion`, `tabla_afectada`) values (?,?,?,?)");
            pst.setString(1, "Asignacion de Vehiculo");
            pst.setString(2, fecha);
            pst.setString(3, "Update del Vehiculo con ID: "+abmt.id_vehiculo);
            pst.setString(4, "Vehiculos");
            pst.executeUpdate();
            cn.close();
            Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
            int valor = JOptionPane.showConfirmDialog(null, "Se ha asignado correctamente", "Asignacion Correcta", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
            abmt.setVisible(true);
            dispose();
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error al guardar ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_asignarActionPerformed

    private void boton_buscar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar3ActionPerformed

        menuVehiculos p = new menuVehiculos();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscar3ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignacionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignacionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignacionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignacionVehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(bajasBienesMuebles_tabla.class.getName()).log(Level.SEVERE, null, ex);
                }
                new asignacionVehiculos().setVisible(true);
            }
        });
    }
    
        public void cerrar() {
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Seguro de cerrar esta ventana?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            menuBienesMuebles p = new menuBienesMuebles();
            p.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> barra_destino;
    private javax.swing.JButton boton_asignar;
    private javax.swing.JButton boton_buscar3;
    private javax.swing.JLabel etq_cilindraje;
    private javax.swing.JLabel etq_encargado;
    private javax.swing.JLabel etq_kilometraje;
    private javax.swing.JLabel etq_marca;
    private javax.swing.JLabel etq_modelo;
    private javax.swing.JLabel etq_motor;
    private javax.swing.JLabel etq_noInventario;
    private javax.swing.JLabel etq_placa;
    private javax.swing.JLabel etq_tarjeta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbNoInventario;
    private javax.swing.JLabel lbNoInventario1;
    private javax.swing.JLabel lbNoInventario2;
    private javax.swing.JLabel lbNoInventario3;
    private javax.swing.JLabel lbNoInventario4;
    private javax.swing.JLabel lbNoInventario5;
    private javax.swing.JLabel lbNoInventario6;
    // End of variables declaration//GEN-END:variables
}
