/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_BD;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author jo199
 */
public class asignacionBienesMuebles extends javax.swing.JFrame {

    public asignacionBienesMuebles() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoa.png")).getImage());
        cargarEmpleados();
        colocarValores();
        boton_transparente(boton_asignar);
        //cerrar();

    }

    public void cargarEmpleados() {
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("SELECT nombre_empleado, clave_servidor_publico FROM empleados WHERE nombre_empleado not in ('almacen','transferencia')");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                barra_destino.addItem(rs.getObject(1).toString() + ": " + rs.getObject(2).toString());
            }
            cn.close();

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void colocarValores() {
        asignacionBienesMueblesTabla abmt = new asignacionBienesMueblesTabla();
        String id = abmt.id;
        barra_noInventario.setText(id);

        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select no_inventario, descripcion_bien, estado_actual, valor_estimado, tipo_sico_sareco, modelo, no_serie from bienes where id_bien = " + id);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                Object[] fila = new Object[5];//por las columnas que tengo
                barra_noInventario.setText(rs.getObject(1).toString());
                barra_descripcion.setText(rs.getObject(2).toString());
                barra_estado.setText(rs.getObject(3).toString());
                barra_valor.setText(rs.getObject(4).toString());
                barra_tipo.setText(rs.getObject(5).toString());
                barra_modelo.setText(rs.getObject(6).toString());
                barra_noSerie.setText(rs.getObject(7).toString());

                barra_noInventario.disable();
                barra_descripcion.disable();
                barra_estado.disable();
                barra_valor.disable();
                barra_tipo.disable();
                barra_modelo.disable();
                barra_noSerie.disable();
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("La excepcion es: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra_descripcion = new javax.swing.JTextField();
        barra_noSerie = new javax.swing.JTextField();
        barra_valor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        barra_modelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        barra_destino = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        boton_asignar = new javax.swing.JButton();
        barra_noInventario = new javax.swing.JTextField();
        barra_tipo = new javax.swing.JTextField();
        barra_estado = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        boton_buscar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asignacion de Bienes Muebles Datos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        barra_descripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_descripcion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_descripcionActionPerformed(evt);
            }
        });

        barra_noSerie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_noSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_noSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_noSerieActionPerformed(evt);
            }
        });

        barra_valor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_valor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_valorActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Estado actual:");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("No. Inventario:");

        barra_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_modeloActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Valor estimado:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de bien:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Modelo:");

        barra_destino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("No. Serie:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Destino");

        boton_asignar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_asignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/aceptar_100.png"))); // NOI18N
        boton_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_asignarActionPerformed(evt);
            }
        });

        barra_noInventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_noInventario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_noInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_noInventarioActionPerformed(evt);
            }
        });

        barra_tipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_tipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_tipoActionPerformed(evt);
            }
        });

        barra_estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        barra_estado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        barra_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barra_estadoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Asignar");

        boton_buscar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar1.setText("Regresar");
        boton_buscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barra_noInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra_noSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(barra_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(22, 22, 22)
                        .addComponent(barra_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(96, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barra_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barra_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boton_asignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_noInventario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barra_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(barra_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boton_asignar)
                        .addGap(32, 32, 32)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barra_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barra_noSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void barra_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_descripcionActionPerformed

    private void barra_noSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_noSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_noSerieActionPerformed

    private void barra_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_valorActionPerformed

    private void barra_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_modeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_modeloActionPerformed

    private void barra_noInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_noInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_noInventarioActionPerformed

    private void barra_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_tipoActionPerformed

    private void barra_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barra_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barra_estadoActionPerformed

    private void boton_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_asignarActionPerformed
        //Se realiza la asignacion de bienes
        asignacionBienesMueblesTabla abmt = new asignacionBienesMueblesTabla();
        String empleado = barra_destino.getSelectedItem().toString();
        String datos_empleado[] = new String[2];
        StringTokenizer token = new StringTokenizer(empleado, ":");
        while (token.hasMoreTokens()) {
            datos_empleado[0] = token.nextToken();
        }
        System.out.println("Clave: " + datos_empleado[0]);
        System.out.println("Id del bien " + abmt.id);
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("SELECT id_empleado FROM empleados WHERE clave_servidor_publico like '%" + datos_empleado[0].trim() + "%'");
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                String id_empleado = rs.getObject(1).toString();
                System.out.println("Id empleado: " + id_empleado);
                pst = cn.prepareStatement("UPDATE bienes SET id_empleado = ? WHERE id_bien = " + abmt.id);
                pst.setString(1, id_empleado);
                pst.executeUpdate();
                System.out.println("Actualizacion exitosa!");

            }

            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            String fecha = dtf.format(LocalDateTime.now());
            pst = cn.prepareStatement("insert into movimientos (`tipo_movimiento`, `fecha`, `accion`, `tabla_afectada`) values (?,?,?,?)");
            pst.setString(1, "Asignacion de bienes");
            pst.setString(2, fecha);
            pst.setString(3, "Update del bien con ID: " + abmt.id);
            pst.setString(4, "Bienes");
            pst.executeUpdate();
            cn.close();
            Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
            int valor = JOptionPane.showConfirmDialog(null, "Se ha asignado correctamente", "Asignacion Correcta", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
            asignacionBienesMueblesTabla abmt2 = new asignacionBienesMueblesTabla();
            abmt2.setVisible(true);
            dispose();
            
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Error al asignar ", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton_asignarActionPerformed

    private void boton_buscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscar1ActionPerformed

        menuBienesMuebles p = new menuBienesMuebles();
        p.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_boton_buscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(asignacionBienesMuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(asignacionBienesMuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(asignacionBienesMuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(asignacionBienesMuebles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(bajasBienesMuebles_tabla.class.getName()).log(Level.SEVERE, null, ex);
                }
                new asignacionBienesMuebles().setVisible(true);
            }
        });
    }
    //boton_transparente(registrar_boton);

    public void boton_transparente(JButton boton) {
        boton.setOpaque(true);
        boton.setContentAreaFilled(false);
    }

    public void cerrar() {
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Seguro de cerrar esta ventana?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            menuBienesMuebles p = new menuBienesMuebles();
            p.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barra_descripcion;
    private javax.swing.JComboBox<String> barra_destino;
    private javax.swing.JTextField barra_estado;
    private javax.swing.JTextField barra_modelo;
    private javax.swing.JTextField barra_noInventario;
    private javax.swing.JTextField barra_noSerie;
    private javax.swing.JTextField barra_tipo;
    private javax.swing.JTextField barra_valor;
    private javax.swing.JButton boton_asignar;
    private javax.swing.JButton boton_buscar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
