/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_BD;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.JTable.AUTO_RESIZE_OFF;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author jo199
 */
public class bajas_empleados_datos extends javax.swing.JFrame {

    public int id_emp = 0, id = 0;

    /**
     * Creates new form bajas_empleados_datos
     */
    public bajas_empleados_datos() {
        initComponents();
        boton_transparente(boton_baja);
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoa.png")).getImage());
        id_emp = bajas_empleados_tabla.id_empleado;
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(51, 102, 255));
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select "
                    + "id_empleado, "
                    + "nombre_empleado, "
                    + "area, "
                    + "ubicacion, "
                    + "clave_servidor_publico, "
                    + "coordinacion "
                    + "from empleados "
                    + "where id_empleado ='" + id_emp + "' and estatus = 'Activo'");

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_empleado");
                etiqueta_nombre_empleado.setText(rs.getString("nombre_empleado"));
                etiqueta_area.setText(rs.getString("area"));
                etiqueta_ubicacion.setText(rs.getString("ubicacion"));
                etiqueta_clave_s_p.setText(rs.getString("clave_servidor_publico"));
                etiqueta_coordinacion.setText(rs.getString("coordinacion"));

                //fecha.setText(rs.getString("ultima_modificacion"));
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("Error al cargar usuario: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al cargar informacion de empleado", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton_buscar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        etiqueta_nombre_empleado = new javax.swing.JLabel();
        etiqueta_clave_s_p = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiqueta_area = new javax.swing.JLabel();
        etiqueta_coordinacion = new javax.swing.JLabel();
        etiqueta_ubicacion = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        boton_baja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bajas empleados");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(boton_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 102, 35));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Nombre del empleado:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 71, 167, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Clave de Servidor Publico:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 126, -1, -1));

        etiqueta_nombre_empleado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_nombre_empleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_nombre_empleado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(etiqueta_nombre_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 71, 271, 23));

        etiqueta_clave_s_p.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_clave_s_p.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_clave_s_p.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(etiqueta_clave_s_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 271, 23));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Area:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 88, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Coordinacion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Ubicacion:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        etiqueta_area.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_area.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_area.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(etiqueta_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 270, 23));

        etiqueta_coordinacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_coordinacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_coordinacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(etiqueta_coordinacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 270, 23));

        etiqueta_ubicacion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_ubicacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_ubicacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(etiqueta_ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 270, 23));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Borrar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        boton_baja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/no aceptar_100.png"))); // NOI18N
        boton_baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_bajaActionPerformed(evt);
            }
        });
        jPanel1.add(boton_baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

        bajas_empleados_tabla p = new bajas_empleados_tabla();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_bajaActionPerformed
        // TODO add your handling code here:

        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("delete from empleados where id_empleado = '" + id + "'");
            pst.executeUpdate();
            cn.close();

        } catch (Exception e) {
            System.out.println("Error al guardar: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al Dar de baja ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        limpiarCampos();
    }//GEN-LAST:event_boton_bajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bajas_empleados_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bajas_empleados_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bajas_empleados_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bajas_empleados_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bajas_empleados_datos().setVisible(true);
            }
        });
    }

    public void limpiarCampos() {
        Icon icono_correcto = new ImageIcon(getClass().getResource("/imagenes/correcto.png"));
        int valor = JOptionPane.showConfirmDialog(null, "Se ha actualizado la informacion  correctamente", "Baja empleados", JOptionPane.OK_OPTION, JOptionPane.QUESTION_MESSAGE, icono_correcto);
        if (valor == JOptionPane.YES_OPTION) {

        }

        bajas_empleados_tabla p = new bajas_empleados_tabla();
        p.setVisible(true);
        this.dispose();

    }

    public void boton_transparente(JButton boton) {
        boton.setOpaque(true);
        boton.setContentAreaFilled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_baja;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JLabel etiqueta_area;
    private javax.swing.JLabel etiqueta_clave_s_p;
    private javax.swing.JLabel etiqueta_coordinacion;
    private javax.swing.JLabel etiqueta_nombre_empleado;
    private javax.swing.JLabel etiqueta_ubicacion;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
