/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_BD;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.Transferable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author jo199
 */
public class detalles_BienesInformaticos_datos extends javax.swing.JFrame implements ClipboardOwner {

    public int id_bien = 0, id = 0;

    /**
     * Creates new form detalles_BienesInformaticos_datos
     */
    public detalles_BienesInformaticos_datos() {
        initComponents();
        //cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoa.png")).getImage());
        id_bien = detalles_BienesInformaticos_tabla.id_bien;
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select "
                    + "b.id_bien, "
                    + "b.no_inventario, "
                    + "b.descripcion_bien, "
                    + "b.marca, "
                    + "b.estado_actual, "
                    + "b.valor_estimado, "
                    + "b.tipo_sico_sareco,"
                    + "b.modelo, "
                    + "b.no_serie, "
                    + "b.ultima_modificacion "
                    + "from bienes b "
                    + "where b.id_bien ='" + id_bien + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_bien");
                etiqueta_no_inventario.setText(rs.getString("no_inventario"));
                etiqueta_descripcion.setText(rs.getString("descripcion_bien"));
                etiqueta_marca.setText(rs.getString("marca"));
                etiqueta_estado.setText(rs.getString("estado_actual"));//setSelectedItem(rs.getString("estado_actual"));
                etiqueta_valor.setText(rs.getString("valor_estimado"));
                etiqueta_tipo.setText(rs.getString("tipo_sico_sareco"));//.setSelectedItem(rs.getString("tipo_sico_sareco"));
                etiqueta_modelo.setText(rs.getString("modelo"));
                etiqueta_no_serie.setText(rs.getString("no_serie"));
                fecha.setText(rs.getString("ultima_modificacion"));
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("Error al cargar usuario: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al al cargar informacion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        boton_copiar_no_serie = new javax.swing.JButton();
        boton_copiar_modelo = new javax.swing.JButton();
        boton_copiar_tipo_bien = new javax.swing.JButton();
        boton_copiar_valorestimado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        boton_copiar_estadoactual = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        boton_copiar_marca = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        boton_copiar_descripcion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        boton_copiar_no_inventario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiqueta_valor = new javax.swing.JLabel();
        etiqueta_tipo = new javax.swing.JLabel();
        etiqueta_no_serie = new javax.swing.JLabel();
        etiqueta_modelo = new javax.swing.JLabel();
        etiqueta_no_inventario = new javax.swing.JLabel();
        etiqueta_descripcion = new javax.swing.JLabel();
        etiqueta_estado = new javax.swing.JLabel();
        etiqueta_marca = new javax.swing.JLabel();
        boton_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalles Bien Informatico");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ultima Modificacion");

        fecha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fecha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        boton_copiar_no_serie.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_no_serie.setText("Copiar No. Serie ");
        boton_copiar_no_serie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_no_serieActionPerformed(evt);
            }
        });

        boton_copiar_modelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_modelo.setText("Copiar Modelo");
        boton_copiar_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_modeloActionPerformed(evt);
            }
        });

        boton_copiar_tipo_bien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_tipo_bien.setText("Copiar Tipo de Bien");
        boton_copiar_tipo_bien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_tipo_bienActionPerformed(evt);
            }
        });

        boton_copiar_valorestimado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_valorestimado.setText("Copiar Valor");
        boton_copiar_valorestimado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_valorestimadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Estado actual:");

        boton_copiar_estadoactual.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_estadoactual.setText("Copiar Estado Actual");
        boton_copiar_estadoactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_estadoactualActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Valor estimado:");

        boton_copiar_marca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_marca.setText("Copiar Marca");
        boton_copiar_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_marcaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Tipo de bien:");

        boton_copiar_descripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_descripcion.setText("Copiar Descripcion ");
        boton_copiar_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_descripcionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("No. Inventario:");

        boton_copiar_no_inventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_copiar_no_inventario.setText("Copiar No. Inventario ");
        boton_copiar_no_inventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_copiar_no_inventarioActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Modelo:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Marca:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("No. Serie:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Descripcion:");

        etiqueta_valor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_valor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_tipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_tipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_no_serie.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_no_serie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_no_serie.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_modelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_no_inventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_no_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_no_inventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_descripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_descripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_estado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_estado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_marca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqueta_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqueta_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boton_copiar_estadoactual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boton_copiar_valorestimado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(19, 19, 19)
                                .addComponent(etiqueta_no_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(boton_copiar_no_inventario))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(32, 32, 32)
                                .addComponent(etiqueta_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(boton_copiar_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(27, 27, 27)
                                .addComponent(etiqueta_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(boton_copiar_tipo_bien, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(60, 60, 60)
                                .addComponent(etiqueta_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(boton_copiar_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(48, 48, 48)
                                .addComponent(etiqueta_no_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(boton_copiar_no_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(67, 67, 67)
                        .addComponent(etiqueta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(boton_copiar_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(etiqueta_no_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_no_inventario))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etiqueta_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_descripcion))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(etiqueta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_marca)
                    .addComponent(jLabel9))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(etiqueta_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(etiqueta_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(boton_copiar_estadoactual)
                                .addGap(27, 27, 27)
                                .addComponent(boton_copiar_valorestimado)))))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(etiqueta_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_tipo_bien))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(etiqueta_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_modelo))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(etiqueta_no_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_copiar_no_serie))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_copiar_no_serieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_no_serieActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_no_serie.getText());
    }//GEN-LAST:event_boton_copiar_no_serieActionPerformed

    private void boton_copiar_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_modeloActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_modelo.getText());
    }//GEN-LAST:event_boton_copiar_modeloActionPerformed

    private void boton_copiar_tipo_bienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_tipo_bienActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_tipo.getText());
    }//GEN-LAST:event_boton_copiar_tipo_bienActionPerformed

    private void boton_copiar_valorestimadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_valorestimadoActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_valor.getText());
    }//GEN-LAST:event_boton_copiar_valorestimadoActionPerformed

    private void boton_copiar_estadoactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_estadoactualActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_estado.getText());
    }//GEN-LAST:event_boton_copiar_estadoactualActionPerformed

    private void boton_copiar_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_marcaActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_marca.getText());
    }//GEN-LAST:event_boton_copiar_marcaActionPerformed

    private void boton_copiar_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_descripcionActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_descripcion.getText());
    }//GEN-LAST:event_boton_copiar_descripcionActionPerformed

    private void boton_copiar_no_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_copiar_no_inventarioActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_no_inventario.getText());
    }//GEN-LAST:event_boton_copiar_no_inventarioActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

        detalles_BienesInformaticos_tabla p = new detalles_BienesInformaticos_tabla();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detalles_BienesInformaticos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detalles_BienesInformaticos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detalles_BienesInformaticos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detalles_BienesInformaticos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(altasBienesInformaticos.class.getName()).log(Level.SEVERE, null, ex);
                }
                new detalles_BienesInformaticos_datos().setVisible(true);
            }
        });
    }

    public void copiar(String texto) {
        StringSelection txt = new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
    }

    public void cerrar() {
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Seguro de cerrar esta ventana?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            detalles_BienesInformaticos_tabla p = new detalles_BienesInformaticos_tabla();
            p.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_copiar_descripcion;
    private javax.swing.JButton boton_copiar_estadoactual;
    private javax.swing.JButton boton_copiar_marca;
    private javax.swing.JButton boton_copiar_modelo;
    private javax.swing.JButton boton_copiar_no_inventario;
    private javax.swing.JButton boton_copiar_no_serie;
    private javax.swing.JButton boton_copiar_tipo_bien;
    private javax.swing.JButton boton_copiar_valorestimado;
    private javax.swing.JLabel etiqueta_descripcion;
    private javax.swing.JLabel etiqueta_estado;
    private javax.swing.JLabel etiqueta_marca;
    private javax.swing.JLabel etiqueta_modelo;
    private javax.swing.JLabel etiqueta_no_inventario;
    private javax.swing.JLabel etiqueta_no_serie;
    private javax.swing.JLabel etiqueta_tipo;
    private javax.swing.JLabel etiqueta_valor;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
