/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.Conection_BD;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author jo199
 */
public class detalles_vehiculos_datos extends javax.swing.JFrame implements ClipboardOwner{

    public int id_carro = 0, id = 0;

    /**
     * Creates new form detalles_vehiculos_datos
     */
    public detalles_vehiculos_datos() {
        initComponents();
        //cerrar();
        setIconImage(new ImageIcon(getClass().getResource("/imagenes/logoa.png")).getImage());
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellRenderer();
        cellRenderer.setBackground(new Color(51, 102, 255));
        //cerrar();
        id_carro = detalles_vehiculos_tabla.id_vehiculoo;
        try {
            Connection cn = Conection_BD.conexion_bd();
            PreparedStatement pst = cn.prepareStatement("select "
                    + "b.id_vehiculo, "
                    + "b.no_inventario, "
                    + "b.marca, "
                    + "b.modelo, "
                    + "b.kilometraje, "
                    + "b.no_motor, "
                    + "b.no_placa, "
                    + "b.cilindraje, "
                    + "b.tipo_vehiculo, "
                    + "b.tarjeta, "
                    + "e.nombre_empleado, "
                    + "b.descripcion_vehiculo, "
                    + "b.estatus "
                    + "from vehiculos b JOIN empleados e "
                    + "ON (b.id_empleado = e.id_empleado) "
                    + "where b.id_vehiculo ='" + id_carro + "'");

            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id = rs.getInt("id_vehiculo");
                etiqueta_no_inventario.setText(rs.getString("no_inventario"));
                etiqueta_marca.setText(rs.getString("marca"));
                etiqueta_modelo.setText(rs.getString("modelo"));
                etiqueta_kilometraje_actual.setText(rs.getString("kilometraje"));
                etiqueta_no_motor.setText(rs.getString("no_motor"));
                etiqueta_placas.setText(rs.getString("no_placa"));//.setSelectedItem(rs.getString("tipo_sico_sareco"));
                etiqueta_cilindraje.setText(rs.getString("cilindraje"));
                etiqueta_tipo.setText(rs.getString("tipo_vehiculo"));
                etiqueta_tarjeta.setText(rs.getString("tarjeta"));
                etiqueta_descripcion.setText(rs.getString("descripcion_vehiculo"));

                //fecha.setText(rs.getString("ultima_modificacion"));
            }
            cn.close();
        } catch (Exception e) {
            System.out.println("Error al cargar usuario: " + e);
            //JOptionPane.showMessageDialog(Componente, mensaje, título, tipo de mensaje, icono);
            JOptionPane.showMessageDialog(null, "Error al cargar informacion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta_tipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiqueta_cilindraje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        etiqueta_placas = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        etiqueta_tarjeta = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiqueta_descripcion = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        etiqueta_kilometraje_actual = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        etiqueta_modelo = new javax.swing.JLabel();
        etiqueta_marca = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        etiqueta_no_inventario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiqueta_no_motor = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        boton_descripcion = new javax.swing.JButton();
        boton_tarjeta = new javax.swing.JButton();
        boton_tipo = new javax.swing.JButton();
        boton_cilindraje = new javax.swing.JButton();
        boton_placas = new javax.swing.JButton();
        boton_nomotor = new javax.swing.JButton();
        boton_kilometraje = new javax.swing.JButton();
        boton_modelo = new javax.swing.JButton();
        boton_marca = new javax.swing.JButton();
        boton_noinventario = new javax.swing.JButton();
        boton_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Detalles Vehiculos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        etiqueta_tipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_tipo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("No. Motor:");

        etiqueta_cilindraje.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_cilindraje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_cilindraje.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("No. Placas:");

        etiqueta_placas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_placas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_placas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Cilindraje: ");

        etiqueta_tarjeta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_tarjeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_tarjeta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Tipo de vehiculo:");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Terminacion de tarjeta asignada:");

        etiqueta_descripcion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_descripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_descripcion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Descripcion: ");

        etiqueta_kilometraje_actual.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_kilometraje_actual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_kilometraje_actual.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("No. Inventario:");

        etiqueta_modelo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_modelo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_modelo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        etiqueta_marca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_marca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_marca.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Marca:");

        etiqueta_no_inventario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_no_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_no_inventario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Modelo:");

        etiqueta_no_motor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta_no_motor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_no_motor.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Kilometraje actual:");

        boton_descripcion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_descripcion.setText("Copiar Descripcion");
        boton_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_descripcionActionPerformed(evt);
            }
        });

        boton_tarjeta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_tarjeta.setText("Copiar Tarjeta");
        boton_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tarjetaActionPerformed(evt);
            }
        });

        boton_tipo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_tipo.setText("Copiar Tipo de vehiculo");
        boton_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_tipoActionPerformed(evt);
            }
        });

        boton_cilindraje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_cilindraje.setText("Copiar Cilindraje");
        boton_cilindraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_cilindrajeActionPerformed(evt);
            }
        });

        boton_placas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_placas.setText("Copiar Placas");
        boton_placas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_placasActionPerformed(evt);
            }
        });

        boton_nomotor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_nomotor.setText("Copiar No. Motor");
        boton_nomotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_nomotorActionPerformed(evt);
            }
        });

        boton_kilometraje.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_kilometraje.setText("Copiar Kilometraje");
        boton_kilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_kilometrajeActionPerformed(evt);
            }
        });

        boton_modelo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_modelo.setText("Copiar Modelo");
        boton_modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_modeloActionPerformed(evt);
            }
        });

        boton_marca.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_marca.setText("Copiar Marca");
        boton_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_marcaActionPerformed(evt);
            }
        });

        boton_noinventario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        boton_noinventario.setText("Copiar No. Inventario");
        boton_noinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_noinventarioActionPerformed(evt);
            }
        });

        boton_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        boton_buscar.setText("Regresar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(140, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(39, 39, 39)
                                .addComponent(etiqueta_no_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_noinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(87, 87, 87)
                                .addComponent(etiqueta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(80, 80, 80)
                                .addComponent(etiqueta_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(14, 14, 14)
                                .addComponent(etiqueta_kilometraje_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_kilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(65, 65, 65)
                                .addComponent(etiqueta_no_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_nomotor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(59, 59, 59)
                                .addComponent(etiqueta_placas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_placas, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(63, 63, 63)
                                .addComponent(etiqueta_cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(22, 22, 22)
                                .addComponent(etiqueta_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(12, 12, 12)
                                .addComponent(etiqueta_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(8, 8, 8)
                                .addComponent(etiqueta_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(boton_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(etiqueta_no_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_noinventario))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(etiqueta_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_marca))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(etiqueta_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_modelo))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(etiqueta_kilometraje_actual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_kilometraje))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(etiqueta_no_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_nomotor))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(etiqueta_placas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_placas))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(etiqueta_cilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_cilindraje))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(etiqueta_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_tipo))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(etiqueta_tarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_tarjeta))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(etiqueta_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_descripcion))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_noinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_noinventarioActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_no_inventario.getText());
    }//GEN-LAST:event_boton_noinventarioActionPerformed

    private void boton_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_marcaActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_marca.getText());
    }//GEN-LAST:event_boton_marcaActionPerformed

    private void boton_modeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_modeloActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_modelo.getText());
    }//GEN-LAST:event_boton_modeloActionPerformed

    private void boton_kilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_kilometrajeActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_kilometraje_actual.getText());
    }//GEN-LAST:event_boton_kilometrajeActionPerformed

    private void boton_nomotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_nomotorActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_no_motor.getText());
    }//GEN-LAST:event_boton_nomotorActionPerformed

    private void boton_placasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_placasActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_placas.getText());
    }//GEN-LAST:event_boton_placasActionPerformed

    private void boton_cilindrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_cilindrajeActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_cilindraje.getText());
    }//GEN-LAST:event_boton_cilindrajeActionPerformed

    private void boton_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tipoActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_tipo.getText());
    }//GEN-LAST:event_boton_tipoActionPerformed

    private void boton_tarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_tarjetaActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_tarjeta.getText());
    }//GEN-LAST:event_boton_tarjetaActionPerformed

    private void boton_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_descripcionActionPerformed
        // TODO add your handling code here:
        copiar(etiqueta_descripcion.getText());
    }//GEN-LAST:event_boton_descripcionActionPerformed

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed

        detalles_vehiculos_tabla p = new detalles_vehiculos_tabla();
            p.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_boton_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detalles_vehiculos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detalles_vehiculos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detalles_vehiculos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detalles_vehiculos_datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(detalles_vehiculos_datos.class.getName()).log(Level.SEVERE, null, ex);
                }
                new detalles_vehiculos_datos().setVisible(true);
            }
        });
    }

    public void copiar(String texto) {
        StringSelection txt = new StringSelection(texto);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(txt, this);
    }
        public void cerrar() {
        try {
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter() {
                public void windowClosing(WindowEvent e) {
                    confirmarSalida();
                }
            });
            //this.setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public void confirmarSalida() {
        int valor = JOptionPane.showConfirmDialog(this, "¿Seguro de cerrar esta ventana?", "ADVERTENCIA", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            detalles_vehiculos_tabla p = new detalles_vehiculos_tabla();
            p.setVisible(true);
            this.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_cilindraje;
    private javax.swing.JButton boton_descripcion;
    private javax.swing.JButton boton_kilometraje;
    private javax.swing.JButton boton_marca;
    private javax.swing.JButton boton_modelo;
    private javax.swing.JButton boton_noinventario;
    private javax.swing.JButton boton_nomotor;
    private javax.swing.JButton boton_placas;
    private javax.swing.JButton boton_tarjeta;
    private javax.swing.JButton boton_tipo;
    private javax.swing.JLabel etiqueta_cilindraje;
    private javax.swing.JLabel etiqueta_descripcion;
    private javax.swing.JLabel etiqueta_kilometraje_actual;
    private javax.swing.JLabel etiqueta_marca;
    private javax.swing.JLabel etiqueta_modelo;
    private javax.swing.JLabel etiqueta_no_inventario;
    private javax.swing.JLabel etiqueta_no_motor;
    private javax.swing.JLabel etiqueta_placas;
    private javax.swing.JLabel etiqueta_tarjeta;
    private javax.swing.JLabel etiqueta_tipo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
